name: AWS Terraform OIDC Workflow

on:
  push:
    branches:
      - "main"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::891377244169:role/githuboicdrole
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      # Step 3: Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 4: Terraform Initialization
      - name: Terraform Init
        run: |
          set -e
          terraform init

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: |
          set -e
          terraform plan -out=tfplan

      # Step 6: Terraform Apply
      - name: Terraform Apply
        run: |
          set -e
          terraform apply -auto-approve tfplan

      # Step 7: Destroy Resources (Optional, Comment out if not needed)
      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' # Run only on manual trigger
        run: |
          set -e
          terraform destroy -auto-approve
